#!/usr/bin/env python3
"""Config converters for the AX6S layout migration.

  convert.py bundle  <backup-root> <out-dir>   build /tmp/restore payload from an extracted sysupgrade backup
  convert.py podkop  <old-config> <new-config> convert podkop 0.4.x config to the 0.7.x format
"""
import os
import shlex
import sys


# ---------------------------------------------------------------- UCI parser

def _tokenize(text):
    """Yield statements (lists of tokens). Handles '..', "..", adjacent quoting, multi-line values, comments."""
    stmt, tok, have_tok = [], [], False
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == "'":
            j = text.index("'", i + 1)
            tok.append(text[i + 1:j]); have_tok = True; i = j + 1
        elif c == '"':
            i += 1
            while text[i] != '"':
                if text[i] == '\\' and i + 1 < n:
                    i += 1
                tok.append(text[i]); i += 1
            have_tok = True; i += 1
        elif c == '\\' and i + 1 < n and text[i + 1] != '\n':
            tok.append(text[i + 1]); have_tok = True; i += 2
        elif c == '#' and not have_tok:
            while i < n and text[i] != '\n':
                i += 1
        elif c in ' \t\r\n':
            if have_tok:
                stmt.append(''.join(tok)); tok, have_tok = [], False
            if c == '\n' and stmt:
                yield stmt; stmt = []
            i += 1
        else:
            tok.append(c); have_tok = True; i += 1
    if have_tok:
        stmt.append(''.join(tok))
    if stmt:
        yield stmt


class Section:
    def __init__(self, stype, name):
        self.type, self.name = stype, name
        self.opts = {}   # name -> str | list[str]
        self.order = []

    def set(self, k, v):
        if k not in self.opts:
            self.order.append(k)
        self.opts[k] = v

    def add(self, k, v):
        cur = self.opts.get(k)
        if not isinstance(cur, list):
            cur = []
        cur.append(v)
        self.set(k, cur)

    def get(self, k, default=None):
        return self.opts.get(k, default)

    def getlist(self, k):
        v = self.opts.get(k)
        if v is None:
            return []
        return v if isinstance(v, list) else v.split()


def parse(path):
    with open(path, encoding='utf-8') as f:
        text = f.read()
    sections, cur = [], None
    for st in _tokenize(text):
        kw = st[0]
        if kw == 'config':
            cur = Section(st[1], st[2] if len(st) > 2 else None)
            sections.append(cur)
        elif kw == 'option' and cur is not None and len(st) >= 2:
            cur.set(st[1], st[2] if len(st) > 2 else '')
        elif kw == 'list' and cur is not None and len(st) >= 3:
            cur.add(st[1], st[2])
    return sections


def q(v):
    return "'" + v.replace("'", "'\\''") + "'"


def dump(sections):
    out = []
    for s in sections:
        out.append('\nconfig %s%s' % (s.type, ' ' + q(s.name) if s.name else ''))
        for k in s.order:
            v = s.opts[k]
            if isinstance(v, list):
                out.extend('\tlist %s %s' % (k, q(x)) for x in v)
            else:
                out.append('\toption %s %s' % (k, q(v)))
    return '\n'.join(out) + '\n'


# ---------------------------------------------------------------- restore bundle

PODKOP_DNS = '127.0.0.42'
WIFI_DEV_SKIP = {'type', 'path', 'phy', 'band', 'hwmode', 'macaddr'}


def _band(dev):
    b = dev.get('band')
    if b:
        return b
    hw = dev.get('hwmode', '')
    return '5g' if hw.endswith('a') or hw.endswith('ac') else '2g'


def wireless_script(path):
    """Emit a shell script that re-applies old wifi settings onto the freshly generated config, matched by band."""
    secs = parse(path)
    devs = {s.name: s for s in secs if s.type == 'wifi-device'}
    lines = ['#!/bin/sh',
             '# generated by convert.py: old wifi config mapped onto new radios by band',
             'radio() { uci show wireless | sed -n "s/^wireless\\.\\([^.]*\\)\\.band=\'$1\'$/\\1/p" | head -1; }']
    for name, dev in devs.items():
        band, var = _band(dev), 'R_' + name.replace('-', '_')
        lines.append('%s=$(radio %s)' % (var, band))
        lines.append('if [ -n "$%s" ]; then' % var)
        lines.append('  echo "wifi: %s (%s) -> $%s"' % (name, band, var))
        for k in dev.order:
            if k in WIFI_DEV_SKIP:
                continue
            v = dev.opts[k]
            if isinstance(v, list):
                lines.append('  uci -q delete wireless.$%s.%s' % (var, k))
                lines.extend('  uci add_list wireless.$%s.%s=%s' % (var, k, shlex.quote(x)) for x in v)
            else:
                lines.append('  uci set wireless.$%s.%s=%s' % (var, k, shlex.quote(v)))
        lines.append('  for s in $(uci show wireless | sed -n "s/^wireless\\.\\([^.]*\\)\\.device=\'$%s\'$/\\1/p"); do uci delete wireless.$s; done' % var)
        for s in (x for x in secs if x.type == 'wifi-iface' and x.get('device') == name):
            if s.name:
                lines.append('  S=%s; uci set wireless.$S=wifi-iface' % shlex.quote(s.name))
            else:
                lines.append('  S=$(uci add wireless wifi-iface)')
            lines.append('  uci set wireless.$S.device="$%s"' % var)
            for k in s.order:
                if k == 'device':
                    continue
                v = s.opts[k]
                if isinstance(v, list):
                    lines.extend('  uci add_list wireless.$S.%s=%s' % (k, shlex.quote(x)) for x in v)
                else:
                    lines.append('  uci set wireless.$S.%s=%s' % (k, shlex.quote(v)))
        lines.append('else')
        lines.append('  echo "wifi: WARNING no %s radio found for %s"' % (band, name))
        lines.append('fi')
    lines.append('uci commit wireless')
    return '\n'.join(lines) + '\n'


SERVERS_FILE = '/etc/dnsmasq.servers'


def _drop(s, k):
    if k in s.opts:
        del s.opts[k]; s.order.remove(k)


def sanitize_dhcp(path):
    """Prepare dhcp for the fresh system. Returns (dhcp config, dnsmasq.servers content).

    - podkop hooks are dropped: podkop is not installed yet, 127.0.0.42 would leave LAN without DNS;
    - domain-specific forwards (/domain/ip) move to a servers file: podkop owns the 'server' list
      while running (keeps only 127.0.0.42) and would disable or drop them.
    """
    secs = parse(path)
    moved = []
    for s in (x for x in secs if x.type == 'dnsmasq'):
        servers = s.getlist('server')
        had_podkop = PODKOP_DNS in servers
        movable = s.get('serversfile') in (None, '', SERVERS_FILE)
        keep = []
        for x in servers:
            if x == PODKOP_DNS:
                continue
            if x.startswith('/') and movable:
                moved.append('server=' + x)
            else:
                keep.append(x)
        if keep:
            s.set('server', keep)
        else:
            _drop(s, 'server')
        if had_podkop and s.get('noresolv') == '1' and not keep:
            _drop(s, 'noresolv')
        if moved and not s.get('serversfile'):
            s.set('serversfile', SERVERS_FILE)
        for k in [k for k in s.order if k.startswith('podkop_')]:
            _drop(s, k)
        break  # podkop manages only @dnsmasq[0]
    return dump(secs), ('\n'.join(moved) + '\n') if moved else ''


def set_compat(path):
    secs = parse(path)
    for s in secs:
        if s.type == 'system':
            s.set('compat_version', '2.0')
            break
    return dump(secs)


def bundle(root, out):
    os.makedirs(out, exist_ok=True)
    cfg = os.path.join(root, 'etc/config')

    def write(name, data, mode=0o644):
        p = os.path.join(out, name)
        with open(p, 'w', encoding='utf-8') as f:
            f.write(data)
        os.chmod(p, mode)
        print('  %s' % name)

    def read(rel):
        with open(os.path.join(root, rel), encoding='utf-8') as f:
            return f.read()

    for name in ('network', 'firewall'):
        if os.path.exists(os.path.join(cfg, name)):
            write(name, read('etc/config/' + name))
    if os.path.exists(os.path.join(cfg, 'dhcp')):
        dhcp, servers = sanitize_dhcp(os.path.join(cfg, 'dhcp'))
        old_file = os.path.join(root, SERVERS_FILE.lstrip('/'))
        if os.path.exists(old_file):
            with open(old_file, encoding='utf-8') as f:
                servers = f.read() + servers
        write('dhcp', dhcp)
        if servers:
            write('dnsmasq.servers', servers)
    if os.path.exists(os.path.join(cfg, 'system')):
        write('system', set_compat(os.path.join(cfg, 'system')))
    if os.path.exists(os.path.join(cfg, 'wireless')):
        write('wireless.sh', wireless_script(os.path.join(cfg, 'wireless')), 0o755)
    for key in ('dropbear_ed25519_host_key', 'dropbear_rsa_host_key', 'dropbear_ecdsa_host_key', 'authorized_keys'):
        p = os.path.join(root, 'etc/dropbear', key)
        if os.path.exists(p):
            with open(p, 'rb') as f, open(os.path.join(out, key), 'wb') as g:
                g.write(f.read())
            os.chmod(os.path.join(out, key), 0o600)
            print('  %s' % key)
    if os.path.exists(os.path.join(root, 'etc/shadow')):
        for line in read('etc/shadow').splitlines():
            parts = line.split(':')
            if parts[0] == 'root' and len(parts) > 1 and parts[1] not in ('', '*', '!', 'x'):
                write('root_hash', parts[1] + '\n', 0o600)
    if os.path.exists(os.path.join(root, 'etc/rc.local')):
        write('rc.local', read('etc/rc.local'))
    if os.path.exists(os.path.join(root, 'etc/crontabs/root')):
        cron = [l for l in read('etc/crontabs/root').splitlines() if 'podkop' not in l]
        if any(l.strip() for l in cron):
            write('crontab', '\n'.join(cron) + '\n')


# ---------------------------------------------------------------- podkop 0.4.x -> 0.7.x

SETTINGS_DEFAULTS = [
    ('dns_type', 'udp'), ('dns_server', '77.88.8.8'), ('bootstrap_dns_server', '77.88.8.8'),
    ('dns_rewrite_ttl', '60'), ('source_network_interfaces', ['br-lan']),
    ('enable_output_network_interface', '0'), ('enable_badwan_interface_monitoring', '0'),
    ('enable_yacd', '0'), ('disable_quic', '0'), ('update_interval', '1d'),
    ('download_lists_via_proxy', '0'), ('dont_touch_dhcp', '0'),
    ('config_path', '/etc/sing-box/config.json'), ('cache_path', '/tmp/sing-box/cache.db'),
    ('log_level', 'warn'), ('exclude_ntp', '0'), ('shutdown_correctly', '0'),
]
DROPPED = {'split_dns_enabled', 'split_dns_type', 'split_dns_server', 'cache_file', 'detour',
           'procd_reload_delay', 'dont_touch_dhcp'}


def _on(s, k):
    return s.get(k) in ('1', 'true', 'on', 'yes')


def podkop(old_path, new_path):
    old = [s for s in parse(old_path) if s.type != 'settings']
    if not old:
        sys.exit('no podkop sections in %s' % old_path)
    main = next((s for s in old if s.name == 'main'), old[0])
    warn = []

    st = Section('settings', 'settings')
    for k, v in SETTINGS_DEFAULTS:
        st.set(k, v)
    for ok, nk in (('dns_type', 'dns_type'), ('dns_server', 'dns_server'), ('dns_rewrite_ttl', 'dns_rewrite_ttl'),
                   ('quic_disable', 'disable_quic'), ('exclude_ntp', 'exclude_ntp'),
                   ('update_interval', 'update_interval'), ('yacd', 'enable_yacd')):
        if main.get(ok) is not None:
            st.set(nk, main.get(ok))
    if main.getlist('iface'):
        st.set('source_network_interfaces', main.getlist('iface'))
    if _on(main, 'mon_restart_ifaces') and main.getlist('restart_ifaces'):
        st.set('enable_badwan_interface_monitoring', '1')
        st.set('badwan_monitored_interfaces', main.getlist('restart_ifaces'))
    if _on(main, 'exclude_from_ip_enabled') and main.getlist('exclude_traffic_ip'):
        st.set('routing_excluded_ips', main.getlist('exclude_traffic_ip'))

    out = [st]
    for s in old:
        n = Section('section', s.name or 'main')
        mode = s.get('mode', 'proxy')
        n.set('connection_type', mode)
        if mode == 'vpn':
            n.set('interface', s.get('interface', ''))
        elif mode == 'proxy':
            n.set('proxy_config_type', s.get('proxy_config_type', 'url'))
            if s.get('proxy_config_type') == 'outbound':
                n.set('outbound_json', s.get('outbound_json', ''))
            else:
                n.set('proxy_string', s.get('proxy_string', ''))
            n.set('enable_udp_over_tcp', s.get('ss_uot', '0'))
        lists = []
        if _on(s, 'domain_list_enabled'):
            lists += s.getlist('domain_list')
        if _on(s, 'subnets_list_enabled'):
            lists += [x for x in s.getlist('subnets') if x not in lists]
        if lists:
            n.set('community_lists', lists)

        dt = s.get('custom_domains_list_type', 'disabled')
        if dt == 'dynamic' and s.getlist('custom_domains'):
            n.set('user_domain_list_type', 'dynamic'); n.set('user_domains', s.getlist('custom_domains'))
        elif dt == 'text' and s.get('custom_domains_text'):
            n.set('user_domain_list_type', 'text'); n.set('user_domains_text', s.get('custom_domains_text'))
        st_ = s.get('custom_subnets_list_enabled', 'disabled')
        if st_ == 'dynamic' and s.getlist('custom_subnets'):
            n.set('user_subnet_list_type', 'dynamic'); n.set('user_subnets', s.getlist('custom_subnets'))
        elif st_ == 'text' and s.get('custom_subnets_text'):
            n.set('user_subnet_list_type', 'text'); n.set('user_subnets_text', s.get('custom_subnets_text'))

        for flag, lst, nk in (('custom_local_domains_list_enabled', 'custom_local_domains', 'local_domain_lists'),
                              ('custom_download_domains_list_enabled', 'custom_download_domains', 'remote_domain_lists'),
                              ('custom_download_subnets_list_enabled', 'custom_download_subnets', 'remote_subnet_lists')):
            if _on(s, flag) and s.getlist(lst):
                n.set(nk, s.getlist(lst))
        if _on(s, 'all_traffic_from_ip_enabled') and s.getlist('all_traffic_ip'):
            n.set('fully_routed_ips', s.getlist('all_traffic_ip'))
        if _on(s, 'socks5'):
            n.set('mixed_proxy_enabled', '1'); n.set('mixed_proxy_port', '2080')
            warn.append('socks5 -> mixed proxy on port 2080 (%s)' % n.name)
        for k in s.order:
            if k in DROPPED and s.get(k) not in (None, '0', 'disabled'):
                warn.append('dropped option %s=%s (%s)' % (k, '<set>' if 'string' in k else s.get(k), n.name))
        out.append(n)

    with open(new_path, 'w', encoding='utf-8') as f:
        f.write(dump(out))
    os.chmod(new_path, 0o600)
    for w in warn:
        print('podkop: ' + w)


if __name__ == '__main__':
    if len(sys.argv) != 4 or sys.argv[1] not in ('bundle', 'podkop'):
        sys.exit(__doc__)
    {'bundle': bundle, 'podkop': podkop}[sys.argv[1]](sys.argv[2], sys.argv[3])
